services:
  # Frontend Network app (Angular)
  network:
    build:
      context: ./network
      dockerfile: Dockerfile
    container_name: network_frontend
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE}/network
        target: /app
      - type: volume
        source: network_node_modules
        target: /app/node_modules
      - type: bind
        source: ${HOST_WORKSPACE}/network/certs
        target: /app/certs
        read_only: true
    ports:
      - "4200:4200"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - devnetwork
    depends_on:
      - bff-network

  # BFF Network (Express.js â€“ Auth + Proxy)
  bff-network:
    build:
      context: ./bff-network
      dockerfile: Dockerfile
    container_name: bff_network
    volumes:
      - type: bind
        source: ${HOST_WORKSPACE}/bff-network
        target: /app
      - type: volume
        source: bff_network_node_modules
        target: /app/node_modules
      - type: bind
        source: ${HOST_WORKSPACE}/bff-network/certs
        target: /app/certs
        read_only: true
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - SESSION_STORE=redis
      - BACKEND_API_URL=http://backend-api:8080
    networks:
      - devnetwork
    depends_on:
      - keycloak
      - redis
      - backend-api

  # Java Spring Boot Backend (Business Logic)
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: network_backend_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - devnetwork
    restart: unless-stopped

  redis:
    extends:
      file: ./redis/docker-compose.yaml
      service: redis

  redis-commander:
    extends:
      file: ./redis/docker-compose.yaml
      service: redis-commander
    depends_on:
      - redis

  postgres:
    extends:
      file: ./keycloak/docker-compose.yaml
      service: postgres

  keycloak:
    extends:
      file: ./keycloak/docker-compose.yaml
      service: keycloak
    depends_on:
      postgres:
        condition: service_healthy

networks:
  devnetwork:
    driver: bridge

# networks:
  # devnetwork:
    # external: true

volumes:
  postgres_data:
  test_data:
  import_dir:
  redis_data:
  network_node_modules:
  bff_network_node_modules:
