stages:

# ---------------------------------------------------------------------------------------------------------
# Qualité du code: tests unitaires, qualité du code et couverture du code
# ---------------------------------------------------------------------------------------------------------

  - template: templates/quality.yml
  - template: templates/static-analysis.yml

# ---------------------------------------------------------------------------------------------------------
# Scan de sécurité (Scan de vulnérabilité )
# ---------------------------------------------------------------------------------------------------------
  - template: templates/security.yml

# ---------------------------------------------------------------------------------------------------------
# Étapes de compilation
# ---------------------------------------------------------------------------------------------------------

  - template: templates/build.yml